local_backend: true

backend:
  name: github
  repo: marquinhusgoncalves/marquinhusgoncalves.com
  branch: master
  site_domain: marquinhusgoncalves.com

media_folder: static/assets/img
public_folder: /assets/img

collections:
  - name: posts
    label: Posts
    folder: posts
    create: true
    slug: '{{slug}}'
    fields:
      - { label: Título, name: title, widget: string }
      - { label: Data, name: date, widget: datetime, format: 'YYYY-MM-DD HH:mm:ss', date_format: DD/MM/YYYY, time_format: HH:mm }
      - { label: Slug, name: slug, widget: string }
      - { label: Tags, name: tags, widget: list, required: false }
      - { label: 'Descrição (SEO)', name: description, widget: text, required: false }
      - { label: Conteúdo, name: body, widget: markdown }

  - name: projects
    label: Projetos
    folder: projects
    create: true
    slug: '{{slug}}'
    fields:
      - { label: Título, name: title, widget: string }
      - { label: Descrição, name: description, widget: text, required: false }
      - { label: URL, name: href, widget: string, required: false }
      - { label: Tags, name: tags, widget: list, required: false }

  - name: dicas
    label: Dicas
    folder: dicas
    create: true
    slug: '{{slug}}'
    fields:
      - { label: Título, name: title, widget: string }
      - { label: Data, name: date, widget: datetime, format: 'YYYY-MM-DD HH:mm:ss', date_format: DD/MM/YYYY, time_format: HH:mm }
      - { label: Slug, name: slug, widget: string }
      - { label: Tags, name: tags, widget: list, required: false }
      - { label: Conteúdo, name: body, widget: markdown }

  - name: viagens
    label: Viagens
    folder: viagens
    create: true
    slug: '{{slug}}'
    fields:
      - { label: Título, name: title, widget: string }
      - { label: Data, name: date, widget: datetime, format: 'YYYY-MM-DD HH:mm:ss', date_format: DD/MM/YYYY, time_format: HH:mm }
      - { label: Slug, name: slug, widget: string }
      - { label: Tags, name: tags, widget: list, required: false }
      - { label: Conteúdo, name: body, widget: markdown }
