backend:
  name: github
  repo: marquinhusgoncalves/marquinhusgoncalves.com
  branch: master
  site_domain: marquinhusgoncalves.com

publish_mode: editorial_workflow
media_folder: static/assets/img
public_folder: /assets/img

collections:
  - name: 'posts'
    label: 'posts'
    folder: 'posts'
    create: true
    slug: '{{slug}}'
    fields:
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Date', name: 'date', widget: 'datetime' }
      - { label: 'Slug', name: 'slug', widget: 'string' }
      - { label: 'Body', name: 'body', widget: 'markdown' }

  - name: 'projects'
    label: 'projects'
    folder: 'projects'
    create: true
    fields:
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'description', name: 'description', widget: 'string' }
      - { label: 'href', name: 'href', widget: 'string' }

  - name: 'dicas'
    label: 'dicas'
    folder: 'dicas'
    create: true
    slug: '{{slug}}'
    fields:
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Date', name: 'date', widget: 'datetime' }
      - { label: 'Slug', name: 'slug', widget: 'string' }
      - { label: 'Body', name: 'body', widget: 'markdown' }

  - name: 'viagens'
    label: 'viagens'
    folder: 'viagens'
    create: true
    slug: '{{slug}}'
    fields:
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Date', name: 'date', widget: 'datetime' }
      - { label: 'Slug', name: 'slug', widget: 'string' }
      - { label: 'Body', name: 'body', widget: 'markdown' }
